### ISSUE TITLE
Suggestion for improvement of functionality

### ISSUE THREAD

**Issue by HoBeom** [Vincentqyw/cv-arxiv-daily#3]
First of all, thank you for creating a promising action pipeline. It's very useful for me.

With the recent launch of ChatGPT, a language model that builds summaries serves as APIs.
How about an automated function that scans and summarizes newly added papers and reviews them in blog post format?

**Comment by Vincentqyw** [comment]
Thanks for the suggestion. I noticed there is a tool named  [ChatPDF](https://www.chatpdf.com/) to quickly extract information from large PDF files, I have plans to add this feature to this repo. BTW, If you have any good ideas, welcome to create a PR.

**Comment by Vincentqyw** [comment]
Another project to summarize the arXiv papers: [ChatPaper](https://github.com/kaixindelele/ChatPaper)
![](https://user-images.githubusercontent.com/28528386/224890637-62be8d42-813c-40ff-8c69-90bb13080e21.png)

**Comment by HoBeom** [comment]
Thank you for your positive feedback. I will also develop and introduce good functions.
