### ISSUE TITLE
Can not update the table of Contents

### ISSUE THREAD

**Issue by doublepoints** [Vincentqyw/cv-arxiv-daily#5]
Hi, I have tried to add some new key words to the search list.
After I add the new key words and rename the existed keywords,
I have found the original keywords has been kept on the table of Contents.
Can you give me some suggestions?
Thank you very much.

**Comment by Vincentqyw** [comment]
Sorry for the late reply, I am working on another project these days.
This script does not support updating Keywords currently, 
if you have any ideas, PR is welcome.
